unset LD
unset LDFLAGS

make bl2 bl31 rcar_layout_tool rcar_srecord PLAT=rcar SPD=opteed MBEDTLS_COMMON_MK=1 LSI=H3 RCAR_DRAM_SPLIT=1 RCAR_DRAM_LPDDR4_MEMCONF=0 RCAR_LOSSY_ENABLE=0 RCAR_GEN3_ULCB=1 PMIC_LEVEL_MODE=0
